# Generated by Django 3.2.6 on 2022-05-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='acceptance_letter',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='degree',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='embassy_fee_reciept',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='insurance',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='passport',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='transcript',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='university_fee_reciept',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
