# Generated by Django 3.2.6 on 2022-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20220523_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='bank_statement',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='dath_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='e_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='passport_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sponser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
